name: Daily AI Email Generator

on:
  schedule:
    # Runs daily at 08:30 UTC (~4:30 AM Eastern while EDT is in effect).
    - cron: '30 8 * * *'
  workflow_dispatch: {}

jobs:
  build-and-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run generator
        run: node index.js

      - name: Commit generated output (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output || true
          if ! git diff --cached --quiet; then
            git commit -m "Daily AI email: $(date -u +'%Y-%m-%d')"
            git push origin HEAD
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
